### ISSUE TITLE
Support for ExpressRoute Gateway sku type

### ISSUE THREAD

**Issue by dnychennnn** [Azure/terraform-azurerm-avm-ptn-vnetgateway#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, I'd like to setup erg with this module but noticed that the sku types won't pass the validation. I've proposed a PR #14 to address this.

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_network_gateway

### Potential Terraform Configuration

```hcl
Included in the PR #14 

variable "sku" {
  type        = string
  description = "The SKU (size) of the Virtual Network Gateway."

  validation {
    condition     = contains(["Basic", "HighPerformance", "Standard", "UltraPerformance", "VpnGw1", "VpnGw2", "VpnGw3", "VpnGw4", "VpnGw5", "VpnGw1AZ", "VpnGw2AZ", "VpnGw3AZ", "VpnGw4AZ", "VpnGw5AZ", "ErGw3AZ"], var.sku)
    error_message = "sku possible values are Basic, HighPerformance, Standard, UltraPerformance, VpnGw1, VpnGw2, VpnGw3, VpnGw4, VpnGw5, VpnGw1AZ, VpnGw2AZ, VpnGw3AZ, VpnGw4AZ, VpnGw5AZ, ErGw3AZ."
  }
}
```

### References
![Uploading image.png…]()

_No response_

**Comment by luke-taylor** [comment]
Thanks for raising this and the subsequent PR, I'll look to see this merged.
