### ISSUE TITLE
express_route_circuits variable validation

### ISSUE THREAD

**Issue by dnychennnn** [Azure/terraform-azurerm-avm-ptn-vnetgateway#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.6.5

### Module Version

0.2.0

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network_gateway_connection

### Terraform Configuration Files

```hcl
module "express_route_gateway_desen" {
  source  = "Azure/avm-ptn-vnetgateway/azurerm"
  version = "0.2.0"
  location                            = var.location
  name                                = local.ergw_name
  sku                                 = ""
  subnet_address_prefix               = var.gateway_snet_prefix
  type                                = "ExpressRoute"
  virtual_network_name                = local.vnet_name
  virtual_network_resource_group_name = local.rg_name
  ip_configurations = {
    ip_config_0 = {
      public_ip = {
        allocation_method = "Static"
        sku = "Standard"
      }
    }
  }
  express_route_circuits = {
    desen = {
      id = local.erc_id
      connection = {
        express_route_gateway_bypass = true
        authorization_key = local.authorization_key
        name = local.connection_name
        routing_weight = local.routing_weight
      }
    }
  }
}
```

### tfvars variables values

```hcl
Not important
```

### Debug Output/Panic Output

```shell
peering_type possible values are AzurePrivatePeering, AzurePublicPeering or MicrosoftPeering.
```

### Expected Behaviour

In our case, setting up a connection for an express route gateway to an express route circuit doesn't require a peering configuration. But here in the validation whenever a `express_route_circuits` variable is specified, the `peering_type` should exist as well.

logic: https://github.com/Azure/terraform-azurerm-avm-ptn-vnetgateway/blob/d7ab874f460c1b70bdc565b4bc637ddda8686780/variables.tf#L125-L128

**Comment by luke-taylor** [comment]
Thank you for spotting this bug, this condition should only evaluate if and only if `peering` is not null, I'll look to put a fix in shortly.
