### ISSUE TITLE
Unable to set `shared_key` for vpn_connections.

### ISSUE THREAD

**Issue by jz-wilson** [Azure/terraform-azurerm-avm-ptn-vnetgateway#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to set `shared_key` for vpn_connections when using a sensitive value. 

```
╷
│ Error: Invalid for_each argument
│
│   on .terraform/modules/vgw/main.tf line 163, in resource "azurerm_virtual_network_gateway_connection" "vgw":
│  163:   for_each = local.virtual_network_gateway_connections
│     ├────────────────
│     │ local.virtual_network_gateway_connections has a sensitive value
│
│ Sensitive values, or values derived from sensitive values, cannot be used as for_each arguments. If used, the sensitive value could be exposed as a resource instance key.
╵
Error running terraform apply : exit status 
```

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_network_gateway_connection.vgw

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network_gateway_connection" "vgw" {
  for_each = nonsensitive(local.virtual_network_gateway_connections)
  ...
}
```

**Comment by luke-taylor** [comment]
@jz-wilson Thanks for raising this, we'll look into some potential workarounds

**Comment by luke-taylor** [comment]
@jz-wilson, can you please provide tfvars file you used (omitting the obvious) to help me reproduce this error. Thanks.

**Comment by jz-wilson** [comment]
I am using `local.local_network_gateways` and the module `terraform-aws-modules/vpn-gateway/aws`. The `shared_key` is sensitive so when that is set it doesn't allow it to be created. When you set the shared key to something manual like "blah" it doesn't error. I think you can test using the resource `random.password.result` as that should be a `sensitive` value.

```
  local_network_gateways = {
    ("${module.vpn_gateway["aws"].vpn_connection_id}-tunnel1") = {
      name            = "${module.vpn_gateway["aws"].vpn_connection_id}-tunnel1"
      gateway_address = module.vpn_gateway["aws"].vpn_connection_tunnel1_address
      address_space   = ["10.28.0.0/16"]
      connection      = {
        name                = "${module.vpn_gateway["aws"].vpn_connection_id}-tunnel1"
        type                = "IPsec"
        enable_bgp          = false
        dpd_timeout_seconds = 45
        shared_key          = module.vpn_gateway["aws"].tunnel1_preshared_key
      }
}
```

**Comment by luke-taylor** [comment]
Thanks, looking to get a PR in this week.
