### ISSUE TITLE
Support for custom resource group

### ISSUE THREAD

**Issue by wplj** [Azure/terraform-azurerm-avm-ptn-vnetgateway#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,
VPN gateway resource uses the same resource group as VNet resource it is hosted in. It's sometimes not quite convenient - the lifecycle of different resource types (app resources, general networking and VPN connectivity) may be different, and it's easier to design/test deployments having some logical boundaries within the same workload.
Please provide a possibility to specify a custom resource group name for VPN Gateway and related resources.

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_network_gateway

**Comment by wplj** [comment]
Maybe it also makes sense to incorporate this (unrelated) change, to keep up with Azurerm updates:
```                                                                                                                                                
│ Warning: Argument is deprecated                                                                                                                
│                                                                                                                                                
│   with module.avm-ptn-vnetgateway.azurerm_route_table.vgw[0],                                                                                  
│   on .terraform\modules\avm-ptn-vnetgateway\main.tf line 16, in resource "azurerm_route_table" "vgw":                                          
│   16:   disable_bgp_route_propagation = !var.route_table_bgp_route_propagation_enabled                                                         
│                                                                                                                                                
│ The property `**disable_bgp_route_propagation**` has been superseded by the property `**bgp_route_propagation_enabled**` and will be removed in v4.0 of the AzureRM Provider.                                                                                                                          
```

**Comment by luke-taylor** [comment]
Hey @wplj, I think this is a reasonable request. I'll look to bundle it all in the next release

**Comment by luke-taylor** [comment]
Upon testing, the gateway cannot be created in resource group that differs from the virtual network. Have you an example where this isn't the case?
