### ISSUE TITLE
Optional Gateway Subnet creation

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/terraform-azurerm-avm-ptn-vnetgateway#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is a common pattern for the virtual network to include the definition for the Gateway Subnet.  Please make the Gateway Subnet creation optional to support this pattern.

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

### Potential Terraform Configuration

```hcl
Include a new input for gatewaySubnet resource ID.  If resource ID is null then proceed to create the subnet.
```

**Comment by luke-taylor** [comment]
Hey, you can already do this with the `subnet_id` variable.

**Comment by jchancellor-ms** [comment]
That's my miss.  Looked right past it.  I'll close, thanks.
