### ISSUE TITLE
[AVM Module Issue]: Random Provider is constraint to "~> 3.5.0"

### ISSUE THREAD

**Issue by jgenicot** [Azure/terraform-azurerm-avm-ptn-vnetgateway#99]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

v0.6.1

### Conflict in Provider Versions Between AVM Modules

Hello AVM Module Team,

#### Issue Description
I am currently integrating multiple AVM modules into a larger solution, but I've encountered a version conflict with the `hashicorp/random` provider that affects deployment. Specifically, the conflict occurs between:
- [`terraform-azurerm-avm-res-compute-virtualmachine`](https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine) which requires `hashicorp/random` version `~> 3.6`.
- [`terraform-azurerm-avm-ptn-vnetgateway`](https://github.com/Azure/terraform-azurerm-avm-ptn-vnetgateway) which uses `hashicorp/random` version `~> 3.5.0`.

#### Error Message

`╷ │ Error: Failed to query available provider packages │ │ Could not retrieve the list of available versions for provider hashicorp/random: no available releases match the given constraints >= 3.5.0, ~> 3.5.0, ~> 3.5, ~> 3.6 ╵`

#### Ask:
Could the version constraints for the `hashicorp/random` provider in the involved modules to be more flexible? This would help prevent conflicts when the latest versions of other modules are used.

This issue impacts our ability to deploy updates and integrate solutions efficiently using these modules.

Thank you for all the work you've put into this framework. Your efforts greatly enhance our operational capabilities.

Best regards,
Jeremy

**Comment by simonjulien** [comment]
Hello,

We have the same issue on this specific module as we are switching on AzureRM v4.

Thank you for your efforts to maintain thoses modules.

Regards,
Julien

**Comment by luke-taylor** [comment]
Should be resolved now as part of the v0.6.2 release. Sorry for any inconvenience.
